#! /usr/bin/env zsh


att() {
    [ -n "${TMUX:-}"] &&
        tmux switch-client -t '=TERMINAL' ||
        tmux attach-session -t '=TERMINAL'
    }

if tmux has-session -t '=TERMINAL'; then
    att
    exit 0
fi

tmux new-session -d -s TERMINAL -n CODE
tmux send-keys -t "=TERMINAL:=CODE" "tmux split-window -h; tmux resize-pane -R 20; tmux detach-client" Enter
sleep 0.1
tmux send-keys -t "TERMINAL:0.0" cmatrix Enter
sleep 1
tmux send-keys -t "TERMINAL:0.1" MoveMouse Enter
tmux attach-session -t TERMINAL

att

### Fix the bug! movemouse should execute in your right hand side.

