#!/usr/bin/env zsh
#This script will automatically set up a workspace tmux layout.
#Based on the script written by Martin Tournoji
#Ref: https://www.arp242.net/tmux.html

att() {
	[ -n "${TMUX:-}" ] &&
		tmux switch-client -t '=CODE' ||
		tmux attach-session -t '=CODE'
	}

if tmux has-session -t '=CODE'; then
	att
	exit 0
fi

tmux new-session -d -s CODE -n Fun -c /mnt/c/Users/GAIA/Documents/Project

tmux new-window -n Terminal -c /mnt/c/Users/GAIA/Documents/Project
tmux new-window -n Arduino -c /mnt/c/Users/GAIA/Documents/Project
tmux send-keys -t "=CODE:=Arduino" "tmux split-window -v -c /mnt/c/Users/GAIA/Documents/Project && tmux resize-pane -D 12 && tmux select-pane -U && clear && fortune | cowsay -f ghostbusters" Enter
tmux send-keys -t "=CODE:=Fun" "watch -n 10 happyghost" Enter

att
